M48
; DRILL file {KiCad (6.0.5)} date Thu 19 May 2022 12:34:07 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-19T00:34:07-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.8425Y-2.6772
X4.8425Y-4.6063
X5.3937Y-2.6772
X5.3937Y-4.6063
T0
M30
